[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "--lts"
  NPM_VERSION = "8.19.3"
  YARN_VERSION = "1.22.19"

[[plugins]]
  package = "@netlify/plugin-gatsby"
