[build]
  command = "gatsby build"
  publish = "public/"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "node"
  NPM_VERSION = "6.1.0"
  RUBY_VERSION = "default"
  YARN_FLAGS = "--no-ignore-optional"
  YARN_VERSION = "1.7.0"
