[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "--lts"
  NPM_VERSION = "6.13.0"
  RUBY_VERSION = "default"
  YARN_VERSION = "1.19.1"
